# Generated by Django 4.0.5 on 2022-06-21 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploadpost_delete_uploadimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='images/')),
                ('title', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
