# Generated by Django 4.0.5 on 2022-06-28 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_about_us_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='customer_reviews',
            name='message',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
